# Generated by Django 4.1 on 2022-09-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0003_alter_image_image_alter_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='text_content',
            new_name='text',
        ),
        migrations.AddField(
            model_name='post',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
