# Generated by Django 4.1 on 2022-09-09 06:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('socialmedia', '0004_rename_text_content_reply_text_post_is_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publication_datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reply',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='socialmedia.post'),
        ),
    ]
