# Generated by Django 4.1 on 2022-09-06 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='followers',
            new_name='following',
        ),
        migrations.AlterUniqueTogether(
            name='userfollower',
            unique_together={('user', 'following')},
        ),
    ]
