# Generated by Django 4.1 on 2022-09-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_followers_user_following_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=160, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
